name: Generate Documentation (main)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Clear Composer Cache
        run: composer clear-cache

      - name: Install or Update Composer Dependencies
        run: |
          composer update bc-andreadao/wp-documentor --no-dev
          composer update bc-andreadao/phpdocumentor-markdown --no-dev --with-all-dependencies

      - name: Run shell script to generate documentation
        run: ./generate-docs.sh

      - name: Generate and push documentation
        run: |
          git clone https://$GITHUB_ACTOR:${{ secrets.ACCESS_TOKEN }}@github.com/bc-andreadao/bc-wordpress-reference.git
          cd bc-wordpress-reference
          git fetch origin
          BRANCH_NAME="docs-$(date +'%Y-%m-%d_%H-%M-%S')"
          git checkout main
          git checkout -b $BRANCH_NAME
          rsync -av --ignore-times $GITHUB_WORKSPACE/docs/ pages/
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"s
          git add .
          git commit -m "Update documentation from $(date +'%Y-%m-%d')" || echo "No changes to commit"
          echo "Current branch: $(git branch --show-current)"
          git push -v --set-upstream origin $BRANCH_NAME || {
            echo "Push failed. Current git status:"
            git status
            echo "Remote branches:"
            git branch -r
            exit 1
          }
