name: Generate Documentation (main)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Install wp-documentor
        run: composer require bc-andreadao/wp-documentor:dev-main --dev

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate Documentation in Markdown
        run: vendor/bin/wp-documentor parse src --format=markdown --output=docs/hooks.md

      - name: Run PHPDoc
        run: docker run --rm -v "$(pwd):/data" "phpdoc/phpdoc:3" -d /data/src -t /data/docs/phpdoc

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Markdown to HTML
        run: pandoc docs/hooks.md -o docs/hooks-temp.html

      - name: Inject HTML into Template
        run: |
          cat <<EOF > docs/hooks.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="utf-8">
              <title>Documentation</title>
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <link rel="stylesheet" href="css/normalize.css">
              <link rel="stylesheet" href="css/base.css">
              <link rel="stylesheet" href="css/template.css">
              <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@100;200;300;400;600;700&display=swap">
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/themes/prism-okaidia.css">
          </head>
          <body>
              <header class="phpdocumentor-header">
                  <h1>Documentation</h1>
              </header>
              <main class="phpdocumentor">
          EOF
          
          cat docs/hooks-temp.html >> docs/hooks.html

          cat <<EOF >> docs/hooks.html
              </main>
              <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/prism.min.js"></script>
          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages-reference
