name: Generate Documentation (main)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Install wp-documentor
        run: composer require bc-andreadao/wp-documentor:dev-main --dev

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate Documentation in Markdown
        run: vendor/bin/wp-documentor parse src --format=markdown --output=docs/hooks.md

      - name: Run PHPDoc
        run: docker run --rm -v "$(pwd):/data" "phpdoc/phpdoc:3" -d /data/src -t /data/docs

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Markdown to HTML
        run: pandoc docs/hooks.md -o docs/hooks-temp.html

      - name: Inject HTML into Template
        run: |
          cat <<EOF > docs/hooks.html
          <!DOCTYPE html>
          <html lang="en">
            <head>
                <meta charset="utf-8">
                <title>Documentation</title>
                <meta name="viewport" content="width=device-width, initial-scale=1.0">
                <link rel="icon" href="images/favicon.ico"/>
                <link rel="stylesheet" href="css/normalize.css">
                <link rel="stylesheet" href="css/base.css">
                <link rel="preconnect" href="https://fonts.gstatic.com">
                <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@100;200;300;400;600;700&display=swap" rel="stylesheet">
                <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;600;700&display=swap" rel="stylesheet">
                <link rel="stylesheet" href="css/template.css">
                <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css" integrity="sha256-ybRkN9dBjhcS2qrW1z+hfCxq+1aBdwyQM5wlQoQVt/0=" crossorigin="anonymous" />
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/themes/prism-okaidia.css">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-numbers/prism-line-numbers.css">
                <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-highlight/prism-line-highlight.css">
                <script src="https://cdn.jsdelivr.net/npm/fuse.js@3.4.6"></script>
                <script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
                <script src="js/template.js"></script>
                <script src="js/search.js"></script>
                <script defer src="js/searchIndex.js"></script>
            </head>
            <body id="top">
                <header class="phpdocumentor-header phpdocumentor-section">
                  <h1 class="phpdocumentor-title"><a href="" class="phpdocumentor-title__link">Documentation</a></h1>
                  <input class="phpdocumentor-header__menu-button" type="checkbox" id="menu-button" name="menu-button" />
                  <label class="phpdocumentor-header__menu-icon" for="menu-button">
                  <i class="fas fa-bars"></i>
                  </label>
                  <section data-search-form class="phpdocumentor-search">
                      <label>
                        <span class="visually-hidden">Search for</span>
                        <svg class="phpdocumentor-search__icon" width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <circle cx="7.5" cy="7.5" r="6.5" stroke="currentColor" stroke-width="2"/>
                            <line x1="12.4892" y1="12.2727" x2="19.1559" y2="18.9393" stroke="currentColor" stroke-width="3"/>
                        </svg>
                        <input type="search" class="phpdocumentor-field phpdocumentor-search__field" placeholder="Loading .." disabled />
                      </label>
                  </section>
                  <nav class="phpdocumentor-topnav">
                      <ul class="phpdocumentor-topnav__menu">
                      </ul>
                  </nav>
                </header>
                <main class="phpdocumentor">
                  <div class="phpdocumentor-section">
                      <input class="phpdocumentor-sidebar__menu-button" type="checkbox" id="sidebar-button" name="sidebar-button" />
                      <label class="phpdocumentor-sidebar__menu-icon" for="sidebar-button">
                      Menu
                      </label>
                      <aside class="phpdocumentor-column -three phpdocumentor-sidebar">
                        <section class="phpdocumentor-sidebar__category -namespaces">
                            <h2 class="phpdocumentor-sidebar__category-header">Namespaces</h2>
                            <h4 class="phpdocumentor-sidebar__root-namespace">
                              <a href="namespaces/bigcommerce.html" class="">BigCommerce</a>
                            </h4>
                            <ul class="phpdocumentor-list">
                              <li>
                                  <a href="namespaces/bigcommerce-accounts.html" class="">Accounts</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-amp.html" class="">Amp</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-analytics.html" class="">Analytics</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-api.html" class="">Api</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-assets.html" class="">Assets</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-banners.html" class="">Banners</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-cache.html" class="">Cache</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-cart.html" class="">Cart</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-checkout.html" class="">Checkout</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-cli.html" class="">CLI</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-compatibility.html" class="">Compatibility</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-container.html" class="">Container</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-currency.html" class="">Currency</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-customizer.html" class="">Customizer</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-editor.html" class="">Editor</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-exceptions.html" class="">Exceptions</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-forms.html" class="">Forms</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-functions.html" class="">Functions</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-gift-certificates.html" class="">Gift_Certificates</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-graphql.html" class="">GraphQL</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-import.html" class="">Import</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-logging.html" class="">Logging</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-manager.html" class="">Manager</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-merchant.html" class="">Merchant</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-meta-boxes.html" class="">Meta_Boxes</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-nav-menu.html" class="">Nav_Menu</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-pages.html" class="">Pages</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-post-types.html" class="">Post_Types</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-proxy.html" class="">Proxy</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-rest.html" class="">Rest</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-reviews.html" class="">Reviews</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-rewrites.html" class="">Rewrites</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-schema.html" class="">Schema</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-settings.html" class="">Settings</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-shortcodes.html" class="">Shortcodes</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-taxonomies.html" class="">Taxonomies</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-templates.html" class="">Templates</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-util.html" class="">Util</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-webhooks.html" class="">Webhooks</a>
                              </li>
                              <li>
                                  <a href="namespaces/bigcommerce-widgets.html" class="">Widgets</a>
                              </li>
                            </ul>
                        </section>
                        <section class="phpdocumentor-sidebar__category -packages">
                            <h2 class="phpdocumentor-sidebar__category-header">Packages</h2>
                            <h4 class="phpdocumentor-sidebar__root-namespace">
                              <a href="packages/Application.html" class="">Application</a>
                            </h4>
                            <h4 class="phpdocumentor-sidebar__root-namespace">
                              <a href="packages/BigCommerce.html" class="">BigCommerce</a>
                            </h4>
                            <ul class="phpdocumentor-list">
                              <li>
                                  <a href="packages/BigCommerce-Amp.html" class="">Amp</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Api.html" class="">Api</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Cart.html" class="">Cart</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Checkout.html" class="">Checkout</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-CLI.html" class="">CLI</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Container.html" class="">Container</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Customizer.html" class="">Customizer</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Logging.html" class="">Logging</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Post.html" class="">Post</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Settings.html" class="">Settings</a>
                              </li>
                              <li>
                                  <a href="packages/BigCommerce-Webhooks.html" class="">Webhooks</a>
                              </li>
                            </ul>
                            <h4 class="phpdocumentor-sidebar__root-namespace">
                              <a href="packages/BigCommmerce.html" class="">BigCommmerce</a>
                            </h4>
                        </section>
                        <section class="phpdocumentor-sidebar__category -reports">
                            <h2 class="phpdocumentor-sidebar__category-header">Reports</h2>
                            <h3 class="phpdocumentor-sidebar__root-package"><a href="reports/deprecated.html">Deprecated</a></h3>
                            <h3 class="phpdocumentor-sidebar__root-package"><a href="reports/errors.html">Errors</a></h3>
                            <h3 class="phpdocumentor-sidebar__root-package"><a href="reports/markers.html">Markers</a></h3>
                        </section>
                        <section class="phpdocumentor-sidebar__category -indices">
                            <h2 class="phpdocumentor-sidebar__category-header">Indices</h2>
                            <h3 class="phpdocumentor-sidebar__root-package"><a href="indices/files.html">Files</a></h3>
                        </section>
                      </aside>
          EOF
          
          cat docs/hooks-temp.html >> docs/hooks.html

          cat <<EOF >> docs/hooks.html
                      <section data-search-results class="phpdocumentor-search-results phpdocumentor-search-results--hidden">
                        <section class="phpdocumentor-search-results__dialog">
                            <header class="phpdocumentor-search-results__header">
                              <h2 class="phpdocumentor-search-results__title">Search results</h2>
                              <button class="phpdocumentor-search-results__close"><i class="fas fa-times"></i></button>
                            </header>
                            <section class="phpdocumentor-search-results__body">
                              <ul class="phpdocumentor-search-results__entries"></ul>
                            </section>
                        </section>
                      </section>
                  </div>
                  <a href="index.html#top" class="phpdocumentor-back-to-top"><i class="fas fa-chevron-circle-up"></i></a>
                </main>
                <script>
                  cssVars({});
                </script>
                <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/prism.min.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/autoloader/prism-autoloader.min.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-numbers/prism-line-numbers.min.js"></script>
                <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-highlight/prism-line-highlight.min.js"></script>
            </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages-reference
