name: Generate Documentation (main)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Install wp-documentor
        run: composer require bc-andreadao/wp-documentor:dev-main --dev
      
      - name: Generate Documentation
        run: vendor/bin/wp-documentor parse src --format=markdown --output=docs/hooks.md

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: wp-documentor-docs
          path: docs/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages-hooks
