name: Generate Documentation (main)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Run shell script to generate documentation
        run: ./generate-docs.sh

      - name: Set git remote URL with token for authentication
        run: |
          git remote set-url origin https://your-username:${{ secrets.ACCESS_TOKEN }}@github.com/your-username/repository-name.git

      # - name: Copy generated docs into existing folder
      #   run: |
      #     rsync -av --ignore-existing ./docs/ bc-wordpress-reference/pages/

      - name: Commit and push changes
        run: |
          cd bc-wordpress-reference
          git checkout test
          echo "This is a test file to debug the GitHub Action workflow." > test-debug-file.txt
          git add .
          git commit -m "Update documentation from $(date +'%Y-%m-%d')" || echo "No changes to commit"
          git push origin test
