name: Generate Documentation (main)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        run: composer install --no-dev

      - name: Install wp-documentor
        run: composer require bc-andreadao/wp-documentor:dev-main --dev

      - name: Create docs directory
        run: mkdir -p docs

      - name: Generate Documentation in Markdown
        run: vendor/bin/wp-documentor parse src --format=markdown --output=docs/hooks.md

      - name: Run PHPDoc
        run: docker run --rm -v "$(pwd):/data" "phpdoc/phpdoc:3" -d /data/src -t /data/docs

      - name: Install Pandoc
        run: sudo apt-get install pandoc

      - name: Convert Markdown to HTML
        run: pandoc docs/hooks.md -o docs/hooks-temp.html

      - name: Inject HTML into Template
        run: |
          cat <<EOF > docs/hooks.html
          <!DOCTYPE html>
          <html lang="en">
          <head>
              <meta charset="utf-8">
              <title>Documentation</title>
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <link rel="icon" href="images/favicon.ico"/>
              <link rel="stylesheet" href="css/normalize.css">
              <link rel="stylesheet" href="css/base.css">
              <link rel="preconnect" href="https://fonts.gstatic.com">
              <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@100;200;300;400;600;700&display=swap" rel="stylesheet">
              <link href="https://fonts.googleapis.com/css2?family=Source+Code+Pro:wght@400;600;700&display=swap" rel="stylesheet">
              <link rel="stylesheet" href="css/template.css">
              <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.0/css/all.min.css" integrity="sha256-ybRkN9dBjhcS2qrW1z+hfCxq+1aBdwyQM5wlQoQVt/0=" crossorigin="anonymous" />
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/themes/prism-okaidia.css">
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-numbers/prism-line-numbers.css">
              <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-highlight/prism-line-highlight.css">
              <script src="https://cdn.jsdelivr.net/npm/fuse.js@3.4.6"></script>
              <script src="https://cdn.jsdelivr.net/npm/css-vars-ponyfill@2"></script>
              <script src="js/template.js"></script>
              <script src="js/search.js"></script>
              <script defer src="js/searchIndex.js"></script>
          </head>
          <body>
              <header class="phpdocumentor-header phpdocumentor-section">
                <h1 class="phpdocumentor-title"><a href="" class="phpdocumentor-title__link">Documentation</a></h1>
                <input class="phpdocumentor-header__menu-button" type="checkbox" id="menu-button" name="menu-button" />
                <label class="phpdocumentor-header__menu-icon" for="menu-button">
                    <i class="fas fa-bars"></i>
                </label>
                <section data-search-form class="phpdocumentor-search">
                    <label>
                      <span class="visually-hidden">Search for</span>
                      <svg class="phpdocumentor-search__icon" width="21" height="20" viewBox="0 0 21 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <circle cx="7.5" cy="7.5" r="6.5" stroke="currentColor" stroke-width="2"/>
                        <line x1="12.4892" y1="12.2727" x2="19.1559" y2="18.9393" stroke="currentColor" stroke-width="3"/>
                      </svg>
                      <input type="search" class="phpdocumentor-field phpdocumentor-search__field" placeholder="Loading .." disabled />
                    </label>
                </section>
                <nav class="phpdocumentor-topnav">
                  <ul class="phpdocumentor-topnav__menu"></ul>
                </nav>
              </header>
              <main class="phpdocumentor">
          EOF
          
          cat docs/hooks-temp.html >> docs/hooks.html

          cat <<EOF >> docs/hooks.html
              </main>
              <script>
                cssVars({});
              </script>
              <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/prism.min.js"></script>
              <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/autoloader/prism-autoloader.min.js"></script>
              <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-numbers/prism-line-numbers.min.js"></script>
              <script src="https://cdn.jsdelivr.net/npm/prismjs@1.23.0/plugins/line-highlight/prism-line-highlight.min.js"></script>

          </body>
          </html>
          EOF

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          publish_branch: gh-pages-reference
